spring:
  application:
    name: routing-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/routingdb
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: routing-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083
